name: Build with PlatformIO

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install PlatformIO
        run: pip install -U platformio

      - name: Build project
        run: pio run -v -e esp32dev -e esp32dev-release
        working-directory: microcontroller-src

      - name: Run tests
        run: pio test -v
        working-directory: microcontroller-src

      - name: Upload firmware binaries
        uses: actions/upload-artifact@v4
        with:
          name: firmware-binaries
          path: |
            microcontroller-src/.pio/build/esp32dev/firmware.bin
            microcontroller-src/.pio/build/esp32dev-release/firmware.bin        
